max_width = 80
wrap_comments = true
comment_width = 60
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 12
error_on_line_overflow = true
error_on_unformatted = true
format_strings = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "module"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 10
unstable_features = true
use_field_init_shorthand = true
